version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://fitness_user:fitness_pass@db:5432/fitness_db
    volumes:
      - .:/app
    depends_on:
      - db
    command: uvicorn backend.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=fitness_user
      - POSTGRES_PASSWORD=fitness_pass
      - POSTGRES_DB=fitness_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: